### PR TITLE
Fixed Date() constructor usage

### PR DESCRIPTION
**Pull request by vanodevium**

### CODE REVIEW

**Comment by UnSstrennen** [comment]
Why do you think that your way is better? In JavaScript, I can also use the expressions I have listed.

**Comment by vanodevium** [comment]
In setCookie() you check _expires_ option:

```
if (options.expires instanceof Date) {
  options.expires = options.expires.toUTCString();
}
```

But, `typeof Date(0)` is *string*

Please read documentation [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date)

> Note: The only correct way to instantiate a new Date object is by using the new operator. If you simply call the Date object directly, such as now = Date(), the returned value is a string rather than a Date object.

Anyway, if you pass integer as argument for constructor, it must be milliseconds since 01-01-1970, but in examples you past simple number which means very old dates in the past.

**Comment by UnSstrennen** [comment]
That's not clear.
```
in[0]: Date(3)

out[0]: "Thu May 14 2020 11:47:21 GMT+0300 (Moscow Standard Time)"
```

Anyway, `.toUTCString()` method is used for cases, if function is used with the arguments like you've tried. I'm going to fix readme (refine that you can use any `Date()` constructor format & extend examples with your cases)

**Comment by vanodevium** [comment]
`Date(3) instanceof Date` is forever *false* in Chrome (Version 81.0.4044.138 (Official Build) (64-bit))
So, I can't set _expires_ with this method.

**Comment by UnSstrennen** [comment]
Okay, bug detected, gonna fix

**Pull request merged**
